/*
 * Dati fittizi dei pazienti per la vista clinica.
 * Coprono tutti e 3 i livelli del semaforo (rosso/giallo/verde) così da
 * mostrare ordinamento, indicatori e Vista Dettaglio. Verranno sostituiti
 * dalle query Supabase quando la persistenza sarà disponibile.
 */

import type { ActivitySlice, Patient, SleepPoint } from "@/types/patient";

/* Palette condivisa per le fasce di intensità del Donut "attività motoria". */
const COLORE_INTENSA = "#2563eb";
const COLORE_MODERATA = "#38bdf8";
const COLORE_LEGGERA = "#a5b4fc";
const COLORE_SEDENTARIO = "#e2e8f0";

/** Costruisce una settimana di ore di sonno a partire da 7 valori. */
function settimanaSonno(valori: number[]): SleepPoint[] {
  const giorni = ["Lun", "Mar", "Mer", "Gio", "Ven", "Sab", "Dom"];
  return giorni.map((giorno, i) => ({ giorno, ore: valori[i] }));
}

/** Compone le 4 fasce di attività motoria (minuti nella giornata tipo). */
function attivita(
  intensa: number,
  moderata: number,
  leggera: number,
  sedentario: number,
): ActivitySlice[] {
  return [
    { nome: "Intensa", valore: intensa, colore: COLORE_INTENSA },
    { nome: "Moderata", valore: moderata, colore: COLORE_MODERATA },
    { nome: "Leggera", valore: leggera, colore: COLORE_LEGGERA },
    { nome: "Sedentario", valore: sedentario, colore: COLORE_SEDENTARIO },
  ];
}

export const pazientiFittizi: Patient[] = [
  {
    id: "p1",
    nome: "Giuseppe Conti",
    eta: 78,
    whoqol: { fisico: 28, psicologico: 42, relazioni: 55, ambiente: 60 },
    statoFisico: 9,
    statoPsichico: 6,
    trendPeggioramento: 8,
    urgenzaDialogoAmica: 7,
    sonno: settimanaSonno([4.2, 3.8, 5.1, 4.0, 3.5, 4.4, 3.9]),
    attivita: attivita(5, 20, 60, 355),
    domandeAttive: [
      {
        id: "q1",
        paziente: "Giuseppe Conti",
        dominio: "fisico",
        domanda: "Pressione sistolica oltre soglia: confermare assunzione terapia?",
        stato: "in_attesa",
        timestamp: "07:52",
      },
      {
        id: "q2",
        paziente: "Giuseppe Conti",
        dominio: "psicologico",
        domanda: "Riferito tono dell'umore basso: attivare contatto con il caregiver?",
        stato: "in_corso",
        timestamp: "08:05",
      },
    ],
  },
  {
    id: "p2",
    nome: "Maria Esposito",
    eta: 71,
    whoqol: { fisico: 45, psicologico: 50, relazioni: 48, ambiente: 62 },
    statoFisico: 7,
    statoPsichico: 7,
    trendPeggioramento: 6,
    urgenzaDialogoAmica: 5,
    sonno: settimanaSonno([5.5, 6.0, 5.2, 6.3, 5.8, 6.1, 5.4]),
    attivita: attivita(10, 35, 90, 305),
    domandeAttive: [
      {
        id: "q3",
        paziente: "Maria Esposito",
        dominio: "fisico",
        domanda: "Saturazione in calo nelle ultime 48h: programmare rilevazione extra?",
        stato: "in_attesa",
        timestamp: "08:20",
      },
    ],
  },
  {
    id: "p3",
    nome: "Antonio Russo",
    eta: 66,
    whoqol: { fisico: 58, psicologico: 47, relazioni: 52, ambiente: 65 },
    statoFisico: 6,
    statoPsichico: 7,
    trendPeggioramento: 5,
    urgenzaDialogoAmica: 4,
    sonno: settimanaSonno([6.1, 5.9, 6.4, 6.0, 6.6, 6.2, 6.5]),
    attivita: attivita(15, 45, 110, 270),
    domandeAttive: [
      {
        id: "q4",
        paziente: "Antonio Russo",
        dominio: "psicologico",
        domanda: "Ansia riferita al risveglio: proporre esercizio di respirazione?",
        stato: "risolta",
        timestamp: "07:40",
      },
    ],
  },
  {
    id: "p4",
    nome: "Lucia Bianchi",
    eta: 69,
    whoqol: { fisico: 64, psicologico: 60, relazioni: 58, ambiente: 70 },
    statoFisico: 5,
    statoPsichico: 5,
    trendPeggioramento: 4,
    urgenzaDialogoAmica: 3,
    sonno: settimanaSonno([6.5, 6.8, 7.0, 6.4, 6.9, 7.1, 6.7]),
    attivita: attivita(20, 60, 130, 230),
    domandeAttive: [
      {
        id: "q5",
        paziente: "Lucia Bianchi",
        dominio: "ambiente",
        domanda: "Segnalata difficoltà negli spostamenti domestici: verificare ausili?",
        stato: "in_attesa",
        timestamp: "08:31",
      },
    ],
  },
  {
    id: "p5",
    nome: "Salvatore Greco",
    eta: 62,
    whoqol: { fisico: 75, psicologico: 72, relazioni: 68, ambiente: 74 },
    statoFisico: 3,
    statoPsichico: 4,
    trendPeggioramento: 2,
    urgenzaDialogoAmica: 2,
    sonno: settimanaSonno([7.2, 7.0, 7.5, 7.1, 7.3, 7.6, 7.4]),
    attivita: attivita(30, 75, 150, 185),
    domandeAttive: [],
  },
  {
    id: "p6",
    nome: "Francesca Romano",
    eta: 58,
    whoqol: { fisico: 82, psicologico: 80, relazioni: 78, ambiente: 85 },
    statoFisico: 2,
    statoPsichico: 2,
    trendPeggioramento: 1,
    urgenzaDialogoAmica: 1,
    sonno: settimanaSonno([7.8, 8.0, 7.6, 8.2, 7.9, 8.1, 8.0]),
    attivita: attivita(45, 90, 160, 145),
    domandeAttive: [],
  },
  {
    id: "p7",
    nome: "Domenico Ferrara",
    eta: 73,
    whoqol: { fisico: 70, psicologico: 66, relazioni: 64, ambiente: 71 },
    statoFisico: 4,
    statoPsichico: 3,
    trendPeggioramento: 3,
    urgenzaDialogoAmica: 2,
    sonno: settimanaSonno([6.9, 7.1, 6.7, 7.0, 7.2, 6.8, 7.0]),
    attivita: attivita(25, 65, 140, 210),
    domandeAttive: [
      {
        id: "q6",
        paziente: "Domenico Ferrara",
        dominio: "relazioni",
        domanda: "Riferito isolamento sociale: suggerire attività di gruppo?",
        stato: "risolta",
        timestamp: "07:58",
      },
    ],
  },
  {
    id: "p8",
    nome: "Carmela Russo",
    eta: 81,
    whoqol: { fisico: 24, psicologico: 38, relazioni: 50, ambiente: 56 },
    statoFisico: 9,
    statoPsichico: 7,
    trendPeggioramento: 9,
    urgenzaDialogoAmica: 8,
    sonno: settimanaSonno([3.6, 4.1, 3.3, 4.5, 3.8, 3.5, 4.0]),
    attivita: attivita(0, 15, 50, 375),
    domandeAttive: [
      {
        id: "q7",
        paziente: "Carmela Russo",
        dominio: "fisico",
        domanda: "Glicemia post-prandiale elevata per 3 giorni: rivedere terapia?",
        stato: "in_attesa",
        timestamp: "07:35",
      },
    ],
  },
  {
    id: "p9",
    nome: "Pasquale Rossi",
    eta: 78,
    whoqol: { fisico: 31, psicologico: 40, relazioni: 47, ambiente: 58 },
    statoFisico: 8,
    statoPsichico: 6,
    trendPeggioramento: 8,
    urgenzaDialogoAmica: 6,
    sonno: settimanaSonno([4.0, 3.7, 4.3, 3.9, 4.1, 3.6, 4.2]),
    attivita: attivita(5, 25, 70, 340),
    domandeAttive: [
      {
        id: "q8",
        paziente: "Pasquale Rossi",
        dominio: "fisico",
        domanda: "Frequenza cardiaca a riposo in aumento: programmare ECG?",
        stato: "in_corso",
        timestamp: "08:12",
      },
    ],
  },
  {
    id: "p10",
    nome: "Anna Marino",
    eta: 84,
    whoqol: { fisico: 27, psicologico: 35, relazioni: 44, ambiente: 52 },
    statoFisico: 8,
    statoPsichico: 8,
    trendPeggioramento: 9,
    urgenzaDialogoAmica: 7,
    sonno: settimanaSonno([3.4, 3.9, 3.2, 4.0, 3.6, 3.3, 3.8]),
    attivita: attivita(0, 10, 45, 385),
    domandeAttive: [
      {
        id: "q9",
        paziente: "Anna Marino",
        dominio: "psicologico",
        domanda: "Confusione mattutina riferita dal caregiver: contattare il medico?",
        stato: "in_attesa",
        timestamp: "07:48",
      },
    ],
  },
  {
    id: "p11",
    nome: "Vincenzo Gallo",
    eta: 70,
    whoqol: { fisico: 48, psicologico: 52, relazioni: 50, ambiente: 60 },
    statoFisico: 7,
    statoPsichico: 6,
    trendPeggioramento: 6,
    urgenzaDialogoAmica: 5,
    sonno: settimanaSonno([5.2, 5.6, 5.0, 5.8, 5.4, 5.1, 5.5]),
    attivita: attivita(10, 40, 95, 295),
    domandeAttive: [],
  },
  {
    id: "p12",
    nome: "Teresa Costa",
    eta: 67,
    whoqol: { fisico: 52, psicologico: 49, relazioni: 54, ambiente: 63 },
    statoFisico: 6,
    statoPsichico: 7,
    trendPeggioramento: 6,
    urgenzaDialogoAmica: 4,
    sonno: settimanaSonno([5.7, 5.5, 6.0, 5.4, 5.9, 5.6, 5.8]),
    attivita: attivita(12, 42, 100, 286),
    domandeAttive: [
      {
        id: "q10",
        paziente: "Teresa Costa",
        dominio: "ambiente",
        domanda: "Riferita scarsa aderenza alle misurazioni: inviare promemoria?",
        stato: "in_corso",
        timestamp: "08:25",
      },
    ],
  },
  {
    id: "p13",
    nome: "Giovanni Bruno",
    eta: 75,
    whoqol: { fisico: 50, psicologico: 46, relazioni: 49, ambiente: 59 },
    statoFisico: 6,
    statoPsichico: 6,
    trendPeggioramento: 5,
    urgenzaDialogoAmica: 5,
    sonno: settimanaSonno([5.8, 6.1, 5.6, 6.0, 5.9, 5.7, 6.2]),
    attivita: attivita(15, 48, 105, 272),
    domandeAttive: [],
  },
  {
    id: "p14",
    nome: "Rosa Ferrari",
    eta: 72,
    whoqol: { fisico: 55, psicologico: 53, relazioni: 51, ambiente: 64 },
    statoFisico: 5,
    statoPsichico: 6,
    trendPeggioramento: 5,
    urgenzaDialogoAmica: 4,
    sonno: settimanaSonno([6.0, 6.3, 5.9, 6.2, 6.4, 6.1, 6.0]),
    attivita: attivita(18, 52, 115, 255),
    domandeAttive: [],
  },
  {
    id: "p15",
    nome: "Luigi De Luca",
    eta: 68,
    whoqol: { fisico: 60, psicologico: 55, relazioni: 56, ambiente: 66 },
    statoFisico: 5,
    statoPsichico: 5,
    trendPeggioramento: 4,
    urgenzaDialogoAmica: 4,
    sonno: settimanaSonno([6.3, 6.5, 6.1, 6.6, 6.4, 6.2, 6.7]),
    attivita: attivita(20, 55, 120, 245),
    domandeAttive: [
      {
        id: "q11",
        paziente: "Luigi De Luca",
        dominio: "relazioni",
        domanda: "Riferita solitudine serale: proporre videochiamata con i familiari?",
        stato: "risolta",
        timestamp: "08:02",
      },
    ],
  },
  {
    id: "p16",
    nome: "Concetta Greco",
    eta: 79,
    whoqol: { fisico: 47, psicologico: 50, relazioni: 48, ambiente: 61 },
    statoFisico: 6,
    statoPsichico: 5,
    trendPeggioramento: 5,
    urgenzaDialogoAmica: 5,
    sonno: settimanaSonno([5.5, 5.8, 5.3, 5.9, 5.6, 5.4, 5.7]),
    attivita: attivita(12, 44, 102, 282),
    domandeAttive: [],
  },
  {
    id: "p17",
    nome: "Michele Lombardi",
    eta: 64,
    whoqol: { fisico: 62, psicologico: 58, relazioni: 57, ambiente: 67 },
    statoFisico: 4,
    statoPsichico: 5,
    trendPeggioramento: 5,
    urgenzaDialogoAmica: 3,
    sonno: settimanaSonno([6.4, 6.7, 6.2, 6.8, 6.5, 6.3, 6.6]),
    attivita: attivita(22, 58, 125, 235),
    domandeAttive: [],
  },
  {
    id: "p18",
    nome: "Angela Conti",
    eta: 70,
    whoqol: { fisico: 58, psicologico: 56, relazioni: 55, ambiente: 65 },
    statoFisico: 5,
    statoPsichico: 5,
    trendPeggioramento: 4,
    urgenzaDialogoAmica: 5,
    sonno: settimanaSonno([6.1, 6.4, 6.0, 6.5, 6.2, 6.0, 6.3]),
    attivita: attivita(18, 50, 118, 254),
    domandeAttive: [
      {
        id: "q12",
        paziente: "Angela Conti",
        dominio: "fisico",
        domanda: "Peso in lieve aumento: verificare ritenzione idrica?",
        stato: "in_attesa",
        timestamp: "08:18",
      },
    ],
  },
  {
    id: "p19",
    nome: "Sergio Moretti",
    eta: 66,
    whoqol: { fisico: 66, psicologico: 60, relazioni: 59, ambiente: 68 },
    statoFisico: 4,
    statoPsichico: 4,
    trendPeggioramento: 4,
    urgenzaDialogoAmica: 3,
    sonno: settimanaSonno([6.6, 6.9, 6.4, 7.0, 6.7, 6.5, 6.8]),
    attivita: attivita(25, 62, 130, 223),
    domandeAttive: [],
  },
  {
    id: "p20",
    nome: "Caterina Rizzo",
    eta: 61,
    whoqol: { fisico: 73, psicologico: 70, relazioni: 67, ambiente: 73 },
    statoFisico: 3,
    statoPsichico: 3,
    trendPeggioramento: 3,
    urgenzaDialogoAmica: 2,
    sonno: settimanaSonno([7.0, 7.2, 6.9, 7.3, 7.1, 7.0, 7.4]),
    attivita: attivita(28, 70, 145, 197),
    domandeAttive: [],
  },
  {
    id: "p21",
    nome: "Alfredo Barbieri",
    eta: 77,
    whoqol: { fisico: 68, psicologico: 64, relazioni: 62, ambiente: 70 },
    statoFisico: 4,
    statoPsichico: 3,
    trendPeggioramento: 3,
    urgenzaDialogoAmica: 2,
    sonno: settimanaSonno([6.8, 7.0, 6.6, 7.1, 6.9, 6.7, 7.0]),
    attivita: attivita(24, 64, 138, 214),
    domandeAttive: [],
  },
  {
    id: "p22",
    nome: "Giuseppina Fontana",
    eta: 63,
    whoqol: { fisico: 76, psicologico: 73, relazioni: 70, ambiente: 75 },
    statoFisico: 3,
    statoPsichico: 3,
    trendPeggioramento: 2,
    urgenzaDialogoAmica: 2,
    sonno: settimanaSonno([7.1, 7.4, 7.0, 7.5, 7.2, 7.1, 7.3]),
    attivita: attivita(32, 76, 150, 182),
    domandeAttive: [],
  },
  {
    id: "p23",
    nome: "Mario Santoro",
    eta: 59,
    whoqol: { fisico: 80, psicologico: 76, relazioni: 74, ambiente: 79 },
    statoFisico: 2,
    statoPsichico: 3,
    trendPeggioramento: 2,
    urgenzaDialogoAmica: 1,
    sonno: settimanaSonno([7.5, 7.7, 7.3, 7.8, 7.6, 7.4, 7.7]),
    attivita: attivita(40, 85, 155, 160),
    domandeAttive: [],
  },
  {
    id: "p24",
    nome: "Elena Caruso",
    eta: 56,
    whoqol: { fisico: 84, psicologico: 81, relazioni: 79, ambiente: 84 },
    statoFisico: 2,
    statoPsichico: 2,
    trendPeggioramento: 1,
    urgenzaDialogoAmica: 1,
    sonno: settimanaSonno([7.9, 8.1, 7.7, 8.2, 8.0, 7.8, 8.1]),
    attivita: attivita(48, 92, 162, 138),
    domandeAttive: [],
  },
  {
    id: "p25",
    nome: "Roberto Villa",
    eta: 65,
    whoqol: { fisico: 72, psicologico: 69, relazioni: 66, ambiente: 72 },
    statoFisico: 3,
    statoPsichico: 4,
    trendPeggioramento: 3,
    urgenzaDialogoAmica: 2,
    sonno: settimanaSonno([6.9, 7.1, 6.8, 7.2, 7.0, 6.9, 7.1]),
    attivita: attivita(30, 72, 148, 190),
    domandeAttive: [
      {
        id: "q13",
        paziente: "Roberto Villa",
        dominio: "ambiente",
        domanda: "Segnalata buona aderenza: nessuna azione, solo monitoraggio.",
        stato: "risolta",
        timestamp: "07:51",
      },
    ],
  },
  {
    id: "p26",
    nome: "Filomena Galli",
    eta: 82,
    whoqol: { fisico: 35, psicologico: 41, relazioni: 46, ambiente: 55 },
    statoFisico: 7,
    statoPsichico: 6,
    trendPeggioramento: 7,
    urgenzaDialogoAmica: 6,
    sonno: settimanaSonno([4.4, 4.8, 4.2, 5.0, 4.5, 4.1, 4.7]),
    attivita: attivita(5, 28, 75, 332),
    domandeAttive: [
      {
        id: "q14",
        paziente: "Filomena Galli",
        dominio: "fisico",
        domanda: "Saturazione notturna sotto soglia: valutare ossigenoterapia?",
        stato: "in_attesa",
        timestamp: "07:44",
      },
    ],
  },
  {
    id: "p27",
    nome: "Nicola Ferri",
    eta: 74,
    whoqol: { fisico: 54, psicologico: 51, relazioni: 53, ambiente: 62 },
    statoFisico: 6,
    statoPsichico: 5,
    trendPeggioramento: 5,
    urgenzaDialogoAmica: 4,
    sonno: settimanaSonno([5.9, 6.2, 5.7, 6.3, 6.0, 5.8, 6.1]),
    attivita: attivita(16, 50, 110, 264),
    domandeAttive: [],
  },
  {
    id: "p28",
    nome: "Alessandra Calia",
    eta: 62,
    whoqol: { fisico: 85, psicologico: 35, relazioni: 40, ambiente: 60 },
    statoFisico: 2,
    statoPsichico: 8,
    trendPeggioramento: 5,
    urgenzaDialogoAmica: 7,
    sonno: settimanaSonno([7.0, 6.5, 7.1, 6.8, 7.2, 6.9, 7.0]),
    attivita: attivita(45, 80, 140, 175),
    domandeAttive: [],
  },
];
